### ISSUE TITLE
Typing allows the invalid expression Int + Bool

### ISSUE THREAD

**Issue by elsoroka** [elsoroka/Satisfiability.jl#21]
It's possible to construct an expression of the form `BoolExpr + IntExpr` which is not valid in Z3, thus it should not be constructable in Satisfiability.jl

**Comment by mykelk** [comment]
Do other solvers support this? If so, then maybe we might want the API to allow it, but for the solver to raise an exception if it is not supported by that particular solver.

**Comment by elsoroka** [comment]
This is a good point.
I checked in CVC5 and it appears to be an error there as well. I think more importantly, the specification for the theory of integers (https://smtlib.cs.uiowa.edu/theories-Ints.shtml) says that arithmetic operators (+, -, * etc) only operate on Int expressions, while comparisons (<, > etc) can operate on Int or Bool expressions. So I think it is a bug.

I see how the bug arose -- I implemented the comparison operators first and didn't catch the different typing.

**Comment by elsoroka** [comment]
PLOT TWIST This may not be a bug because as @mykelk said, other solvers can support it -- specifically Z3, where I did most of my testing, allows such statements (while CVC5 does not). I'm going to ask Clark Barrett.

Minimal example:
```
(declare-const x Bool)
(declare-const a Int)
(assert (< 1 (+ a x)))
(check-sat)
(get-model)
```
Z3 outputs
```sat
(
  (define-fun a () Int
    2)
  (define-fun x () Bool
    false)
)
```

Internally, Z3 is replacing `x` in the arithmetic expression with `(ite x 1 0)`. You can see this using the command `(simplify (+ a x))` which outputs `(+ a (ite x 1 0))`.
CVC5 (and probably others) does NOT allow this.

I think for user convenience, the resolution of this "bug" should be to do the Z3 thing and explicitly replace Bool expressions in arithmetic expressions with the if-then-else statement. This would provide Z3's user-friendly behavior while preserving correctness with the SMT-LIB specification as written.
