### ISSUE TITLE
[BUG] IOError

### ISSUE THREAD

**Issue by EveWCheng** [elsoroka/Satisfiability.jl#65]
**Describe the bug**

**Please provide the steps to reproduce the bug, including a minimal code demo if possible.**
I ran the example code block and it produced a bug at line "status = sat!(expr, solver=Z3())". 

**What is the expected behavior?**
It gave the error "IOError: could not spawn `z3 -smt2 -in`: no such file or directory (ENOENT)"

**Please tell us about your environment.**
  A simple way to do this: open Julia and type
  ```
  using InteractiveUtils
  versioninfo()
  ```
  Paste the output of `versioninfo()` into your bug report.
Julia Version 1.10.4

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions on how to fix it)

**Comment by EveWCheng** [comment]
Ah I probably just need z3 installed

**Comment by elsoroka** [comment]
awesome, thanks for flagging this. I think the error message should be more descriptive. Also interesting that Z3 did not install as #43 was supposed to do that.
